import { TripProvider } from '../../../provider/trip-pricing-provider';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return <TripProvider>{children}</TripProvider>;
}

