import {
    Activity,
    Accessibility,
    AlertCircle,
    Anchor,
    Award,
    Baby,
    Backpack,
    Banknote,
    Bed,
    Beer,
    Bike,
    Briefcase,
    Building,
    Bus,
    Calendar,
    CalendarDays,
    Camera,
    Car,
    Check,
    CheckCircle,
    Clock,
    Cloud,
    CloudRain,
    Coffee,
    Compass,
    CreditCard,
    DollarSign,
    Droplet,
    Fish,
    Flag,
    Flame,
    Flower,
    Footprints,
    Gift,
    Globe,
    Headphones,
    Heart,
    HelpCircle,
    Home,
    Hotel,
    Image,
    Info,
    Lock,
    Luggage,
    Mail,
    Map,
    MapPin,
    Maximize,
    Medal,
    Minimize,
    Moon,
    Mountain,
    Music,
    Navigation,
    Palmtree,
    Phone,
    Pizza,
    Plane,
    Search,
    Shield,
    Ship,
    ShoppingBag,
    Star,
    Sun,
    Tag,
    Tent,
    ThumbsUp,
    Ticket,
    Timer,
    Train,
    Trees,
    Trophy,
    Umbrella,
    Unlock,
    User,
    Users,
    Utensils,
    Video,
    Watch,
    Waves,
    Wifi,
    Wind,
    Wine,
    X,
    XCircle,
    Zap,
} from 'lucide-react';
import { BsCardText, BsListCheck } from 'react-icons/bs';
import { GiMoneyStack, GiTakeMyMoney } from 'react-icons/gi';
import { HiListBullet, HiOutlineInformationCircle } from 'react-icons/hi2';
import { IoDocumentTextOutline } from 'react-icons/io5';
import { LuMapPinned } from 'react-icons/lu';
import { MdFreeCancellation, MdLibraryAdd, MdOutlineViewList } from 'react-icons/md';
import { PiClockCountdownFill } from 'react-icons/pi';
import { SlCalender } from 'react-icons/sl';
/**
 * Shared icon mapping for trip sections
 * Used in both TripSummary and ExperienceSection components
 */
export const iconMapping = {
    // Time & Schedule
    calendar: SlCalender,
    location: LuMapPinned,
    clock: PiClockCountdownFill,
    clockIcon: Clock,
    calendarIcon: Calendar,
    calendarDays: CalendarDays,
    timer: Timer,
    watch: Watch,
    
    // PascalCase Aliases for backward compatibility
    Calendar: Calendar,
    CalendarDays: CalendarDays,
    Clock: Clock,
    Timer: Timer,
    Watch: Watch,

    // Location & Travel
    mapPin: MapPin,
    map: Map,
    globe: Globe,
    navigation: Navigation,
    compass: Compass,
    plane: Plane,
    car: Car,
    bus: Bus,
    train: Train,
    ship: Ship,
    anchor: Anchor,
    bike: Bike,
    footprints: Footprints,
    mountain: Mountain,
    palmtree: Palmtree,
    trees: Trees,
    flower: Flower,
    waves: Waves,
    fish: Fish,

    // PascalCase Aliases 
    MapPin: MapPin,
    Map: Map,
    Globe: Globe,
    Navigation: Navigation,
    Compass: Compass,
    Plane: Plane,
    Car: Car,
    Bus: Bus,
    Train: Train,
    Ship: Ship,
    Anchor: Anchor,
    Bike: Bike,
    Footprints: Footprints,
    Mountain: Mountain,
    Palmtree: Palmtree,
    Trees: Trees,
    Flower: Flower,
    Waves: Waves,
    Fish: Fish,

    // Nature & Weather
    sun: Sun,
    moon: Moon,
    cloud: Cloud,
    cloudRain: CloudRain,
    umbrella: Umbrella,
    wind: Wind,
    flame: Flame,
    droplet: Droplet,
    zap: Zap,

    // PascalCase Aliases
    Sun: Sun,
    Moon: Moon,
    Cloud: Cloud,
    CloudRain: CloudRain,
    Umbrella: Umbrella,
    Wind: Wind,
    Flame: Flame,
    Droplet: Droplet,
    Zap: Zap,

    // Activities & Recreation
    camera: Camera,
    video: Video,
    image: Image,
    music: Music,
    headphones: Headphones,
    star: Star,
    heart: Heart,
    thumbsUp: ThumbsUp,
    award: Award,
    medal: Medal,
    trophy: Trophy,
    gift: Gift,

    // PascalCase Aliases
    Camera: Camera,
    Video: Video,
    Image: Image,
    Music: Music,
    Headphones: Headphones,
    Star: Star,
    Heart: Heart,
    ThumbsUp: ThumbsUp,
    Award: Award,
    Medal: Medal,
    Trophy: Trophy,
    Gift: Gift,

    // Food & Drink
    utensils: Utensils,
    coffee: Coffee,
    wine: Wine,
    beer: Beer,
    pizza: Pizza,

    // PascalCase Aliases
    Utensils: Utensils,
    Coffee: Coffee,
    Wine: Wine,
    Beer: Beer,
    Pizza: Pizza,

    // Facilities & Lodging
    bed: Bed,
    tent: Tent,
    hotel: Hotel,
    home: Home,
    building: Building,
    wifi: Wifi,

    // PascalCase Aliases
    Bed: Bed,
    Tent: Tent,
    Hotel: Hotel,
    Home: Home,
    Building: Building,
    Wifi: Wifi,

    // Services & Pricing
    included: MdLibraryAdd,
    money: GiTakeMyMoney,
    cancellation: MdFreeCancellation,
    price: GiMoneyStack,
    dollarSign: DollarSign,
    banknote: Banknote,
    creditCard: CreditCard,
    shield: Shield,
    lock: Lock,
    unlock: Unlock,
    tag: Tag,
    ticket: Ticket,

    // PascalCase Aliases
    DollarSign: DollarSign,
    Banknote: Banknote,
    CreditCard: CreditCard,
    Shield: Shield,
    Lock: Lock,
    Unlock: Unlock,
    Tag: Tag,
    Ticket: Ticket,

    // Communication & People
    users: Users,
    user: User,
    baby: Baby,
    accessibility: Accessibility,
    phone: Phone,
    mail: Mail,
    info: Info,
    helpCircle: HelpCircle,
    alertCircle: AlertCircle,
    check: Check,
    checkCircle: CheckCircle,
    x: X,
    xCircle: XCircle,
    briefcase: Briefcase,
    backpack: Backpack,
    luggage: Luggage,
    shoppingBag: ShoppingBag,
    flag: Flag,
    activity: Activity,

    // PascalCase Aliases
    Users: Users,
    User: User,
    Baby: Baby,
    Accessibility: Accessibility,
    Phone: Phone,
    Mail: Mail,
    Info: Info,
    HelpCircle: HelpCircle,
    AlertCircle: AlertCircle,
    Check: Check,
    CheckCircle: CheckCircle,
    X: X,
    XCircle: XCircle,
    Briefcase: Briefcase,
    Backpack: Backpack,
    Luggage: Luggage,
    ShoppingBag: ShoppingBag,
    Flag: Flag,
    Activity: Activity,

    // Layout Type Specific Icons
    'bullet-list': HiListBullet,
    'check-list': BsListCheck,
    'numbered-list': MdOutlineViewList,
    description: IoDocumentTextOutline,
    'single-paragraph': BsCardText,
    'meeting-info': LuMapPinned,
    'info-card': HiOutlineInformationCircle,
};

/**
 * Icon categories for the icon selector
 * Organized by purpose for easy browsing
 */
export const iconCategories = [
    {
        name: 'Common',
        icons: [
            { value: 'star', label: 'Star', component: Star },
            { value: 'heart', label: 'Heart', component: Heart },
            { value: 'info', label: 'Info', component: Info },
            { value: 'checkCircle', label: 'Check', component: CheckCircle },
            { value: 'alertCircle', label: 'Alert', component: AlertCircle },
            { value: 'zap', label: 'Zap', component: Zap },
            { value: 'flag', label: 'Flag', component: Flag },
        ],
    },
    {
        name: 'Travel & Location',
        icons: [
            { value: 'mapPin', label: 'Map Pin', component: MapPin },
            { value: 'location', label: 'Location Pin', component: LuMapPinned },
            { value: 'map', label: 'Map', component: Map },
            { value: 'globe', label: 'Globe', component: Globe },
            { value: 'navigation', label: 'Navigation', component: Navigation },
            { value: 'compass', label: 'Compass', component: Compass },
            { value: 'plane', label: 'Plane', component: Plane },
            { value: 'ship', label: 'Ship', component: Ship },
            { value: 'anchor', label: 'Anchor', component: Anchor },
            { value: 'car', label: 'Car', component: Car },
            { value: 'bus', label: 'Bus', component: Bus },
            { value: 'train', label: 'Train', component: Train },
            { value: 'bike', label: 'Bike', component: Bike },
            { value: 'footprints', label: 'Footprints', component: Footprints },
        ],
    },
    {
        name: 'Time',
        icons: [
            { value: 'clockIcon', label: 'Clock', component: Clock },
            { value: 'clock', label: 'Countdown', component: PiClockCountdownFill },
            { value: 'calendarIcon', label: 'Calendar', component: Calendar },
            { value: 'calendar', label: 'Calendar Fancy', component: SlCalender },
            { value: 'calendarDays', label: 'Calendar Days', component: CalendarDays },
            { value: 'timer', label: 'Timer', component: Timer },
            { value: 'watch', label: 'Watch', component: Watch },
        ],
    },
    {
        name: 'Nature & Weather',
        icons: [
            { value: 'sun', label: 'Sun', component: Sun },
            { value: 'moon', label: 'Moon', component: Moon },
            { value: 'waves', label: 'Waves', component: Waves },
            { value: 'palmtree', label: 'Palm Tree', component: Palmtree },
            { value: 'mountain', label: 'Mountain', component: Mountain },
            { value: 'trees', label: 'Trees', component: Trees },
            { value: 'flower', label: 'Flower', component: Flower },
            { value: 'fish', label: 'Fish', component: Fish },
            { value: 'cloud', label: 'Cloud', component: Cloud },
            { value: 'cloudRain', label: 'Rain', component: CloudRain },
            { value: 'umbrella', label: 'Umbrella', component: Umbrella },
            { value: 'wind', label: 'Wind', component: Wind },
        ],
    },
    {
        name: 'Food & Drink',
        icons: [
            { value: 'utensils', label: 'Food', component: Utensils },
            { value: 'coffee', label: 'Coffee', component: Coffee },
            { value: 'wine', label: 'Wine', component: Wine },
            { value: 'beer', label: 'Beer', component: Beer },
            { value: 'pizza', label: 'Pizza', component: Pizza },
        ],
    },
    {
        name: 'Objects & Media',
        icons: [
            { value: 'camera', label: 'Camera', component: Camera },
            { value: 'video', label: 'Video', component: Video },
            { value: 'image', label: 'Image', component: Image },
            { value: 'music', label: 'Music', component: Music },
            { value: 'headphones', label: 'Headphones', component: Headphones },
            { value: 'briefcase', label: 'Briefcase', component: Briefcase },
            { value: 'backpack', label: 'Backpack', component: Backpack },
            { value: 'luggage', label: 'Luggage', component: Luggage },
            { value: 'shoppingBag', label: 'Shopping', component: ShoppingBag },
            { value: 'gift', label: 'Gift', component: Gift },
            { value: 'ticket', label: 'Ticket', component: Ticket },
        ],
    },
    {
        name: 'People & Groups',
        icons: [
            { value: 'users', label: 'Groups', component: Users },
            { value: 'user', label: 'Individual', component: User },
            { value: 'baby', label: 'Baby', component: Baby },
            { value: 'accessibility', label: 'Accessible', component: Accessibility },
        ],
    },
    {
        name: 'Lodging & Building',
        icons: [
            { value: 'home', label: 'Home', component: Home },
            { value: 'hotel', label: 'Hotel', component: Hotel },
            { value: 'building', label: 'Building', component: Building },
            { value: 'bed', label: 'Bed', component: Bed },
            { value: 'tent', label: 'Tent', component: Tent },
            { value: 'wifi', label: 'WiFi', component: Wifi },
        ],
    },
    {
        name: 'Money & Payment',
        icons: [
            { value: 'dollarSign', label: 'Dollar', component: DollarSign },
            { value: 'money', label: 'Large Fee', component: GiTakeMyMoney },
            { value: 'price', label: 'Stack', component: GiMoneyStack },
            { value: 'banknote', label: 'Cash', component: Banknote },
            { value: 'creditCard', label: 'Card', component: CreditCard },
            { value: 'tag', label: 'Price Tag', component: Tag },
        ],
    },
    {
        name: 'Safety & Action',
        icons: [
            { value: 'shield', label: 'Shield', component: Shield },
            { value: 'lock', label: 'Lock', component: Lock },
            { value: 'unlock', label: 'Unlock', component: Unlock },
            { value: 'cancellation', label: 'Cancellation', component: MdFreeCancellation },
            { value: 'check', label: 'Simple Check', component: Check },
            { value: 'thumbsUp', label: 'Thumbs Up', component: ThumbsUp },
            { value: 'award', label: 'Award', component: Award },
            { value: 'medal', label: 'Medal', component: Medal },
            { value: 'trophy', label: 'Trophy', component: Trophy },
            { value: 'activity', label: 'Activity', component: Activity },
        ],
    },
    {
        name: 'Layout Icons',
        icons: [
            { value: 'bullet-list', label: 'Bullet List', component: HiListBullet },
            { value: 'check-list', label: 'Check List', component: BsListCheck },
            { value: 'numbered-list', label: 'Numbered List', component: MdOutlineViewList },
            { value: 'description', label: 'Document', component: IoDocumentTextOutline },
            { value: 'single-paragraph', label: 'Paragraph', component: BsCardText },
            { value: 'info-card', label: 'Info Card', component: HiOutlineInformationCircle },
        ],
    },
];

/**
 * Get default icon based on section/layout type
 * @param {string} type - The layout type (e.g., 'bullet-list', 'info-card')
 * @returns {string} - The icon key to use
 */
export const getDefaultIconForType = type => {
    const typeIconMap = {
        'bullet-list': 'bullet-list',
        'check-list': 'check-list',
        'numbered-list': 'numbered-list',
        description: 'description',
        'single-paragraph': 'single-paragraph',
        'meeting-info': 'location',
        'info-card': 'info-card',
    };
    return typeIconMap[type] || 'star';
};
